### ISSUE TITLE
Naver Cafe Free Pass 문의

### ISSUE THREAD

**Issue by SiriPRO** [ucyang/NaverCafeFreePass#11]
특정 멤버 등급도 뚫을수 있게 만들어주세요.
그리고 특정 카페에서는 멤버만 볼수있는거 못 뚫더라고요.
그것도 수정부탁드립니다.

그리고 이런 멋진 프로그렘을 만들어주셔서 감사합니다.

**Comment by ucyang** [comment]
Naver Cafe Free Pass는 검색 허용이 되어 있는 게시글의 차단을 우회하는 프로그램이며, **검색 허용이 되지 않은 게시글의 차단은 우회할 수 없습니다.**

이는 게시글 열람 가능 회원 등급과 같은 기타 요소와는 무관한 부분이며, 해당 게시글의 **검색 허용 여부**만이 중요합니다.

또한, 검색 허용 설정이 명시적으로 해제된 게시글의 내용을 우회적으로 확인하는 기능은 불법의 소지가 다분하기에 구현하기 곤란한 부분입니다.

그러나 만약, 분명히 검색 허용 설정이 되어 있음에도 게시글의 내용을 확인할 수 없는 문제가 발생하시는 경우 자세한 정보(게시글 주소, 브라우저 종류 및 버전, 문제 발생 당시 상황 등)와 함께 추가 문의를 남겨주시면 성실히 답변드리겠습니다.

감사합니다.
